alerts:
  email:
    enabled: true
    recipient_email: 1781051483@qq.com
    sender_email: daydreammy@163.com
    sender_password: NUYQEBJEHZRHGLSI
    smtp_port: 465
    smtp_server: smtp.163.com
  telegram:
    bot_token: xxx
    chat_id: xxx
    enabled: false
message_monitor:
  database:
    path: data/message_monitor.db
    type: sqlite
  storage:
    media_path: data/media
    save_media: true
  target_groups:
  - 48922992214@chatroom
  - 43500136128@chatroom
monitoring:
  check_interval: 30
wechat:
  app_id: wx_AS5eTRwpCC2spVAt9ovsV
  base_url: http://localhost:2531/v2/api
  callback_url: http://192.168.123.249:8069/callback
  token: 7c26f9afbab04fa681d0de588ec0279e
